spring:
  application:
    name: tydic-xj-integration-backend
  datasource:
    url: jdbc:postgresql://10.1.31.111:5432/postgis_yth
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    # 使用druid数据源,后面2个数据源会自动继承这里配置的属性
    type: com.alibaba.druid.pool.DruidDataSource
    # 配置初始化大小、最小、最大
    initial-size: 5
    max-active: 20
    min-idle: 5
    # 配置获取连接等待超时的时间
    max-wait: 60000
    validationQuery: select 1
    test-on-borrow: true
    druid:
      stat-view-servlet:
        login-username: tydic
        login-password: tydic2018
        #23G impala连接
      hive:
        url: jdbc:hive2://10.1.32.54:21050/;auth=noSasl
        driver-class-name: org.apache.hive.jdbc.HiveDriver
        username: impala
        password:
        # 使用druid数据源,后面2个数据源会自动继承这里配置的属性
        type: com.alibaba.druid.pool.DruidDataSource
        # 配置初始化大小、最小、最大
        initial-size: 5
        max-active: 20
        min-idle: 5
        # 配置获取连接等待超时的时间
        max-wait: 60000
        validationQuery: select 1
        test-on-borrow: true
        #23G postgis连接
      netopostgis:
        url: jdbc:postgresql://10.1.32.120:6003/postgis_xj
        driver-class-name: org.postgresql.Driver
        username: postgres
        password: postgres
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        # 配置初始化大小、最小、最大
        initial-size: 5
        max-active: 20
        min-idle: 5
        # 配置获取连接等待超时的时间
        max-wait: 60000
        validationQuery: select 1
        testOnBorrow: true
        #一体化postgis连接
      postgis:
        url: jdbc:postgresql://10.1.31.111:5432/postgis_yth
        driver-class-name: org.postgresql.Driver
        username: postgres
        password: postgres
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        # 配置初始化大小、最小、最大
        initial-size: 5
        max-active: 20
        min-idle: 5
        # 配置获取连接等待超时的时间
        max-wait: 60000
        validationQuery: select 1
        testOnBorrow: true
      mysql:
        url: jdbc:mysql://10.1.21.32:3306/wy_meta_xj?useUnicode=true&characterEncoding=UTF-8
        username: root
        password: root2015
        # 使用druid数据源
        driver-class-name: com.mysql.jdbc.Driver
        # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
        time-between-eviction-runs-millis: 60000
        # 配置一个连接在池中最小生存的时间，单位是毫秒
        min-evictable-idle-time-millis: 300000
        test-while-idle: true
        test-on-return: false
        # 打开PSCache，并且指定每个连接上PSCache的大小
        pool-prepared-statements: true
        filters: stat,wall
        max-open-prepared-statements: 20
        connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
        # 使用druid数据源,后面2个数据源会自动继承这里配置的属性
        type: com.alibaba.druid.pool.DruidDataSource
        # 连接池配置，初始5个
        initial-size: 5
        max-active: 20
        min-idle: 5
        max-wait: 60000
        validationQuery: select 1
        test-on-borrow: true
  redis:
    # redis 缓存时间（秒）
    #cache-time: 600
    host: 127.0.0.1
    port: 6379
    #password: 123456
    pool:
      max-active: 8
      max-wait: -1
      max-idle: 8
      min-idle: 0
    timeout: 0
    database: 1
    #topic: __keyevent@1__:expired
# LOGGING
logging:
    config: classpath:logback-spring.xml
    #file: ${spring.application.name}.log
    path: logs/${spring.application.name}
server:
  port: 8011
  context-path: /tydic-xj-integration-backend
